import { trackSelfDescribingEvent, CommonEventProperties, SelfDescribingJson } from '@snowplow/browser-tracker';
// Automatically generated by Snowtype

/**
 * Entity representing an article.
 */
export type Article = {
    /**
     * The unique identifier for the article.
     */
    article_id: string;
    /**
     * The author of the article.
     */
    author?: null | string;
    /**
     * The category under which the article is classified.
     */
    category?: null | string;
    /**
     * The position of the article in the search results or display.
     */
    position?: number | null;
    /**
     * A list of tags associated with the article.
     */
    tags?: string[] | null;
    /**
     * The title of the article.
     */
    title?: null | string;
    [property: string]: any;
}

/**
 * Details of an advertisement shown or interacted with
 */
export type Ad = {
    /**
     * Identifier of the ad shown or interacted with.
     */
    ad_id: string;
    /**
     * Identifier for the advertiser.
     */
    advertiser_id?: null | string;
    /**
     * ID of the marketing campaign.
     */
    campaign_id?: null | string;
    /**
     * The cost of the ad
     */
    cost?: number | null;
    /**
     * The cost model of the ad
     */
    cost_model?: CostModel;
    /**
     * ID of the creative variation shown.
     */
    creative_id?: null | string;
    /**
     * Where the ad was placed (e.g., header, sidebar, in-feed).
     */
    placement?: Placement;
    /**
     * The position/order in which the ad appeared.
     */
    position?: number | null;
    /**
     * Type of ad, e.g., banner, video, native.
     */
    type?: AdType;
    [property: string]: any;
}

/**
 * The cost model of the ad
 */
export type CostModel = "cpc" | "cpm" | "cpa";

/**
 * Where the ad was placed (e.g., header, sidebar, in-feed).
 */
export type Placement = "header" | "sidebar" | "footer" | "in-feed" | "native" | "search_results" | "content_body" | "video_pre-roll";

/**
 * Type of ad, e.g., banner, video, native.
 */
export type AdType = "banner" | "video" | "native" | "interstitial" | "rich_media" | "sponsored_content" | "search" | "email" | "audio";

/**
 * User receives a response from the agent. Message details are in the attached
 * message_context entity. Agent details are in the attached agent_context entity.
 */
export type MessageReceived = {
    /**
     * Agent invocation that generated this response
     */
    invocation_id: string;
    /**
     * Timestamp when response was received
     */
    received_at: Date;
    /**
     * Time taken to generate response
     */
    response_time_ms: number;
    /**
     * Total tokens used in generation
     */
    tokens_used?: number | null;
    /**
     * Number of tool calls made during this response
     */
    tool_calls_count: number;
}

/**
 * Context entity describing the agent, its configuration, and current state when performing
 * actions.
 */
export type Agent = {
    /**
     * Application version
     */
    application_version?: null | string;
    /**
     * Number of messages in conversation history at this point
     */
    conversation_messages_count?: number | null;
    /**
     * Current step number within the invocation
     */
    current_step_number?: number | null;
    /**
     * Unique identifier for current agent invocation
     */
    invocation_id: string;
    /**
     * LLM model identifier (e.g., claude-sonnet-4-20250514)
     */
    model_name: string;
    /**
     * LLM provider (e.g., anthropic, openai)
     */
    model_provider: string;
    /**
     * Type/name of agent
     */
    type: string;
}

/**
 * Context entity describing a chat message, its content, and metadata. Attached to
 * message_sent and message_received events.
 */
export type Message = {
    /**
     * A session identifier for the chat
     */
    chat_session_id: string;
    /**
     * Turn number in the conversation (pair of user + assistant messages)
     */
    conversation_turn?: number | null;
    /**
     * Unique identifier for this message
     */
    id: string;
    /**
     * Position of this message in the conversation
     */
    index: number;
    /**
     * Length of message in characters
     */
    length: number;
    /**
     * Truncated message content for privacy (first 100 chars)
     */
    preview?: null | string;
    /**
     * Who sent the message (user or AI assistant)
     */
    role: Role;
}

/**
 * Who sent the message (user or AI assistant)
 */
export type Role = "user" | "assistant";

/**
 * User sends a message in the chat interface. Message details are in the attached
 * message_context entity.
 */
export type MessageSent = {
    /**
     * Timestamp when message was sent
     */
    sent_at: Date;
}

/**
 * Captures steps as a user moves through the subscription workflow on a media and
 * publishing site. - Generated from a property rule
 */
export type SubscriptionWorkflowConfirmPayment = {
    /**
     * The name of the step the user is currently on in the subscription workflow.
     */
    step_name: SubscriptionWorkflowConfirmPaymentStepName;
    /**
     * Additional information related to the current step.
     */
    value?: null | string;
}

/**
 * The name of the step the user is currently on in the subscription workflow.
 */
export type SubscriptionWorkflowConfirmPaymentStepName = "confirm_payment";

/**
 * Data structure for when a user interacts with an article - Generated from a property rule
 */
export type ArticleInteractionArticleView = {
    /**
     * The type of article interaction
     */
    type: ArticleInteractionArticleViewType;
}

/**
 * The type of article interaction
 */
export type ArticleInteractionArticleViewType = "view";

/**
 * Captures steps as a user moves through the subscription workflow on a media and
 * publishing site. - Generated from a property rule
 */
export type SubscriptionWorkflowPersonalDetails = {
    /**
     * The name of the step the user is currently on in the subscription workflow.
     */
    step_name: SubscriptionWorkflowPersonalDetailsStepName;
    /**
     * Additional information related to the current step.
     */
    value?: null | string;
}

/**
 * The name of the step the user is currently on in the subscription workflow.
 */
export type SubscriptionWorkflowPersonalDetailsStepName = "personal_details";

/**
 * Data structure for when a user interacts with an advertisement - Generated from a
 * property rule
 */
export type AdInteractionAdClick = {
    /**
     * The type of ad interaction
     */
    type: AdInteractionAdClickType;
}

/**
 * The type of ad interaction
 */
export type AdInteractionAdClickType = "click";

/**
 * Data structure for when a user interacts with an advertisement - Generated from a
 * property rule
 */
export type AdInteractionAdImpression = {
    /**
     * The type of ad interaction
     */
    type: AdInteractionAdImpressionType;
}

/**
 * The type of ad interaction
 */
export type AdInteractionAdImpressionType = "impression";

/**
 * Captures a search action by the user including the search term and resulting metadata. -
 * Generated from a property rule
 */
export type SearchPerformedQuickSearch = {
    search_type?: SearchPerformedQuickSearchSearchType;
    /**
     * The search term entered by the user.
     */
    term: string;
    /**
     * The total number of results returned for the search.
     */
    total_results?: number | null;
}

export type SearchPerformedQuickSearchSearchType = "quick";

/**
 * Entity representing an article. - Generated from a property rule
 */
export type ArticleQuickSearch = {
    /**
     * The unique identifier for the article.
     */
    article_id: string;
    /**
     * The author of the article.
     */
    author?: null | string;
    /**
     * The category under which the article is classified.
     */
    category?: null | string;
    /**
     * The position of the article in the search results or display.
     */
    position?: number | null;
    /**
     * A list of tags associated with the article.
     */
    tags?: string[] | null;
    /**
     * The title of the article.
     */
    title?: null | string;
    [property: string]: any;
}

/**
 * Captures a search action by the user including the search term and resulting metadata. -
 * Generated from a property rule
 */
export type SearchPerformedFullSearch = {
    search_type?: SearchPerformedFullSearchSearchType;
    /**
     * The search term entered by the user.
     */
    term: string;
    /**
     * The total number of results returned for the search.
     */
    total_results?: number | null;
}

export type SearchPerformedFullSearchSearchType = "full";

/**
 * Entity representing an article. - Generated from a property rule
 */
export type ArticleFullSearch = {
    /**
     * The unique identifier for the article.
     */
    article_id: string;
    /**
     * The author of the article.
     */
    author?: null | string;
    /**
     * The category under which the article is classified.
     */
    category?: null | string;
    /**
     * Include where in the results order the article was shown
     */
    position?: number | null;
    /**
     * A list of tags associated with the article.
     */
    tags?: string[] | null;
    /**
     * The title of the article.
     */
    title?: null | string;
    [property: string]: any;
}

/**
 * Captures steps as a user moves through the subscription workflow on a media and
 * publishing site. - Generated from a property rule
 */
export type SubscriptionWorkflowSelectAPlan = {
    /**
     * The name of the step the user is currently on in the subscription workflow.
     */
    step_name: SubscriptionWorkflowSelectAPlanStepName;
    /**
     * Whether the user selects a monthly or annual plan
     */
    value?: Value;
}

/**
 * The name of the step the user is currently on in the subscription workflow.
 */
export type SubscriptionWorkflowSelectAPlanStepName = "select_plan";

/**
 * Whether the user selects a monthly or annual plan
 */
export type Value = "monthly" | "annually";

/**
 * Captures steps as a user moves through the subscription workflow on a media and
 * publishing site. - Generated from a property rule
 */
export type SubscriptionWorkflowEnterSubscriptionFlow = {
    /**
     * The name of the step the user is currently on in the subscription workflow.
     */
    step_name: SubscriptionWorkflowEnterSubscriptionFlowStepName;
    /**
     * Additional information related to the current step.
     */
    value?: null | string;
}

/**
 * The name of the step the user is currently on in the subscription workflow.
 */
export type SubscriptionWorkflowEnterSubscriptionFlowStepName = "begin_workflow";

/**
 * Captures user login attempts for demo purposes. - Generated from a property rule
 */
export type LoginLoginSuccess = {
    /**
     * Reason for login failure, if applicable.
     */
    failure_reason?: null | string;
    /**
     * The method used to attempt login.
     */
    login_method?: LoginMethod;
    login_status?: LoginStatus;
}

/**
 * The method used to attempt login.
 */
export type LoginMethod = "email" | "google" | "facebook" | "apple";

export type LoginStatus = "success";

/**
 * Creates a Snowplow Event Specification entity.
 */
export function createEventSpecification(eventSpecification: Omit<EventSpecification, 'data_product_domain'> & Partial<Pick<EventSpecification, 'data_product_domain'>>){
    return {
        schema:
            'iglu:com.snowplowanalytics.snowplow/event_specification/jsonschema/1-0-4',
        data: eventSpecification,
    }
}

/**
 * Automatically attached context for event specifications
 */
interface EventSpecification {
    id: string;
    version: number;
    name: string;
    data_product_id: string;
    data_product_name: string;
    data_product_domain?: string;
}

type ContextsOrTimestamp<T = any> = Omit<CommonEventProperties<T>, 'context'> & { context?: SelfDescribingJson<T>[] | null | undefined }
/**
 * Track a Snowplow event for Article.
 * Entity representing an article.
 */
export function trackArticle<T extends {} = any>(article: Article & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = article;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo.media/article/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow Article entity.
 */
export function createArticle(article: Article){
    return {
        schema: 'iglu:com.demo.media/article/jsonschema/1-0-0',
        data: article
    }
}
/**
 * Track a Snowplow event for Ad.
 * Details of an advertisement shown or interacted with
 */
export function trackAd<T extends {} = any>(ad: Ad & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = ad;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/ad/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow Ad entity.
 */
export function createAd(ad: Ad){
    return {
        schema: 'iglu:com.demo/ad/jsonschema/1-0-0',
        data: ad
    }
}
/**
 * Track a Snowplow event for MessageReceived.
 * User receives a response from the agent. Message details are in the attached message_context entity. Agent details are in the attached agent_context entity.
 */
export function trackMessageReceived<T extends {} = any>(messageReceived: MessageReceived & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = messageReceived;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/message_received/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow MessageReceived entity.
 */
export function createMessageReceived(messageReceived: MessageReceived){
    return {
        schema: 'iglu:com.demo/message_received/jsonschema/1-0-0',
        data: messageReceived
    }
}
/**
 * Track a Snowplow event for Agent.
 * Context entity describing the agent, its configuration, and current state when performing actions.
 */
export function trackAgent<T extends {} = any>(agent: Agent & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = agent;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/agent/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow Agent entity.
 */
export function createAgent(agent: Agent){
    return {
        schema: 'iglu:com.demo/agent/jsonschema/1-0-0',
        data: agent
    }
}
/**
 * Track a Snowplow event for Message.
 * Context entity describing a chat message, its content, and metadata. Attached to message_sent and message_received events.
 */
export function trackMessage<T extends {} = any>(message: Message & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = message;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/message/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow Message entity.
 */
export function createMessage(message: Message){
    return {
        schema: 'iglu:com.demo/message/jsonschema/1-0-0',
        data: message
    }
}
/**
 * Track a Snowplow event for MessageSent.
 * User sends a message in the chat interface. Message details are in the attached message_context entity.
 */
export function trackMessageSent<T extends {} = any>(messageSent: MessageSent & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = messageSent;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/message_sent/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow MessageSent entity.
 */
export function createMessageSent(messageSent: MessageSent){
    return {
        schema: 'iglu:com.demo/message_sent/jsonschema/1-0-0',
        data: messageSent
    }
}
/**
 * Track a Snowplow event for SubscriptionWorkflowConfirmPayment.
 * Captures steps as a user moves through the subscription workflow on a media and publishing site. - Generated from a property rule
 */
function trackSubscriptionWorkflowConfirmPayment<T extends {} = any>(subscriptionWorkflowConfirmPayment: SubscriptionWorkflowConfirmPayment & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = subscriptionWorkflowConfirmPayment;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo.media/subscription_workflow/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for ArticleInteractionArticleView.
 * Data structure for when a user interacts with an article - Generated from a property rule
 */
function trackArticleInteractionArticleView<T extends {} = any>(articleInteractionArticleView: ArticleInteractionArticleView & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = articleInteractionArticleView;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo.media/article_interaction/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for SubscriptionWorkflowPersonalDetails.
 * Captures steps as a user moves through the subscription workflow on a media and publishing site. - Generated from a property rule
 */
function trackSubscriptionWorkflowPersonalDetails<T extends {} = any>(subscriptionWorkflowPersonalDetails: SubscriptionWorkflowPersonalDetails & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = subscriptionWorkflowPersonalDetails;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo.media/subscription_workflow/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for AdInteractionAdClick.
 * Data structure for when a user interacts with an advertisement - Generated from a property rule
 */
function trackAdInteractionAdClick<T extends {} = any>(adInteractionAdClick: AdInteractionAdClick & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = adInteractionAdClick;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/ad_interaction/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for AdInteractionAdImpression.
 * Data structure for when a user interacts with an advertisement - Generated from a property rule
 */
function trackAdInteractionAdImpression<T extends {} = any>(adInteractionAdImpression: AdInteractionAdImpression & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = adInteractionAdImpression;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/ad_interaction/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for SearchPerformedQuickSearch.
 * Captures a search action by the user including the search term and resulting metadata. - Generated from a property rule
 */
function trackSearchPerformedQuickSearch<T extends {} = any>(searchPerformedQuickSearch: SearchPerformedQuickSearch & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = searchPerformedQuickSearch;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/search_performed/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow ArticleQuickSearch entity.
 */
export function createArticleQuickSearch(articleQuickSearch: ArticleQuickSearch){
    return {
        schema: 'iglu:com.demo.media/article/jsonschema/1-0-0',
        data: articleQuickSearch
    }
}
/**
 * Track a Snowplow event for SearchPerformedFullSearch.
 * Captures a search action by the user including the search term and resulting metadata. - Generated from a property rule
 */
function trackSearchPerformedFullSearch<T extends {} = any>(searchPerformedFullSearch: SearchPerformedFullSearch & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = searchPerformedFullSearch;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/search_performed/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Creates a Snowplow ArticleFullSearch entity.
 */
export function createArticleFullSearch(articleFullSearch: ArticleFullSearch){
    return {
        schema: 'iglu:com.demo.media/article/jsonschema/1-0-0',
        data: articleFullSearch
    }
}
/**
 * Track a Snowplow event for SubscriptionWorkflowSelectAPlan.
 * Captures steps as a user moves through the subscription workflow on a media and publishing site. - Generated from a property rule
 */
function trackSubscriptionWorkflowSelectAPlan<T extends {} = any>(subscriptionWorkflowSelectAPlan: SubscriptionWorkflowSelectAPlan & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = subscriptionWorkflowSelectAPlan;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo.media/subscription_workflow/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for SubscriptionWorkflowEnterSubscriptionFlow.
 * Captures steps as a user moves through the subscription workflow on a media and publishing site. - Generated from a property rule
 */
function trackSubscriptionWorkflowEnterSubscriptionFlow<T extends {} = any>(subscriptionWorkflowEnterSubscriptionFlow: SubscriptionWorkflowEnterSubscriptionFlow & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = subscriptionWorkflowEnterSubscriptionFlow;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo.media/subscription_workflow/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}

/**
 * Track a Snowplow event for LoginLoginSuccess.
 * Captures user login attempts for demo purposes. - Generated from a property rule
 */
function trackLoginLoginSuccess<T extends {} = any>(loginLoginSuccess: LoginLoginSuccess & ContextsOrTimestamp<T>, trackers?: string[]){
    const { context, timestamp, ...data } = loginLoginSuccess;
    const event: SelfDescribingJson = {
        schema: 'iglu:com.demo/login/jsonschema/1-0-0',
        data
    };

    trackSelfDescribingEvent({
        event,
        context,
        timestamp,
    }, trackers);
}


/**
 * Tracks a ConfirmPayment event specification.
 * ID: 05f604ca-af39-4f32-8b81-d35ec7c17720
 */
export function trackConfirmPaymentSpec(confirmPayment: SubscriptionWorkflowConfirmPayment & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '05f604ca-af39-4f32-8b81-d35ec7c17720',
        version: 6,
        name: 'Confirm Payment',
        data_product_id: 'ead1f30f-1234-4350-a112-02003991e391',
        data_product_name: 'Customer Acquisition',
        data_product_domain: 'Marketing'
    });

    const context = Array.isArray(confirmPayment.context)
        ? [...confirmPayment.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedConfirmPayment = {
        ...confirmPayment,
        context,
    };

    trackSubscriptionWorkflowConfirmPayment<Record<string, unknown> | EventSpecification>(modifiedConfirmPayment, trackers);
}
/**
 * Tracks a ArticleView event specification.
 * ID: 207d6f27-a125-402a-b515-d40064d0f1c4
 */
export function trackArticleViewSpec(articleView: ArticleInteractionArticleView & ContextsOrTimestamp<Article>, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '207d6f27-a125-402a-b515-d40064d0f1c4',
        version: 10,
        name: 'Article View',
        data_product_id: '98f633e6-ab32-43a8-8e07-0d6124da0ee7',
        data_product_name: 'Editorial Content Engagement',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(articleView.context)
        ? [...articleView.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedArticleView = {
        ...articleView,
        context,
    };

    trackArticleInteractionArticleView<Article | EventSpecification>(modifiedArticleView, trackers);
}
/**
 * Tracks a PersonalDetails event specification.
 * ID: 3962b139-d376-4ff3-9554-e78df3332676
 */
export function trackPersonalDetailsSpec(personalDetails: SubscriptionWorkflowPersonalDetails & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '3962b139-d376-4ff3-9554-e78df3332676',
        version: 3,
        name: 'Personal Details',
        data_product_id: 'ead1f30f-1234-4350-a112-02003991e391',
        data_product_name: 'Customer Acquisition',
        data_product_domain: 'Marketing'
    });

    const context = Array.isArray(personalDetails.context)
        ? [...personalDetails.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedPersonalDetails = {
        ...personalDetails,
        context,
    };

    trackSubscriptionWorkflowPersonalDetails<Record<string, unknown> | EventSpecification>(modifiedPersonalDetails, trackers);
}
/**
 * Tracks a AdClick event specification.
 * ID: 5f04be54-cc64-4e50-90f6-a85df727a50e
 */
export function trackAdClickSpec(adClick: AdInteractionAdClick & ContextsOrTimestamp<Ad>, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '5f04be54-cc64-4e50-90f6-a85df727a50e',
        version: 7,
        name: 'Ad Click',
        data_product_id: '58526f0a-c5b6-4d08-bc4f-199836217d0c',
        data_product_name: 'Advertising Performance',
        data_product_domain: 'Marketing'
    });

    const context = Array.isArray(adClick.context)
        ? [...adClick.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedAdClick = {
        ...adClick,
        context,
    };

    trackAdInteractionAdClick<Ad | EventSpecification>(modifiedAdClick, trackers);
}
/**
 * Tracks a AdImpression event specification.
 * ID: 6511cf68-d715-4729-b83e-4c7ede68ccbb
 */
export function trackAdImpressionSpec(adImpression: AdInteractionAdImpression & ContextsOrTimestamp<Ad>, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '6511cf68-d715-4729-b83e-4c7ede68ccbb',
        version: 11,
        name: 'Ad Impression',
        data_product_id: '58526f0a-c5b6-4d08-bc4f-199836217d0c',
        data_product_name: 'Advertising Performance',
        data_product_domain: 'Marketing'
    });

    const context = Array.isArray(adImpression.context)
        ? [...adImpression.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedAdImpression = {
        ...adImpression,
        context,
    };

    trackAdInteractionAdImpression<Ad | EventSpecification>(modifiedAdImpression, trackers);
}
/**
 * Tracks a QuickSearch event specification.
 * ID: 73383b45-f16a-4249-b7d1-3edf0731713b
 */
export function trackQuickSearchSpec(quickSearch: SearchPerformedQuickSearch & ContextsOrTimestamp<ArticleQuickSearch>, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '73383b45-f16a-4249-b7d1-3edf0731713b',
        version: 5,
        name: 'Quick Search',
        data_product_id: '98f633e6-ab32-43a8-8e07-0d6124da0ee7',
        data_product_name: 'Editorial Content Engagement',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(quickSearch.context)
        ? [...quickSearch.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedQuickSearch = {
        ...quickSearch,
        context,
    };

    trackSearchPerformedQuickSearch<ArticleQuickSearch | EventSpecification>(modifiedQuickSearch, trackers);
}
/**
 * Tracks a AgentMessage event specification.
 * ID: 79fa7504-66b1-4e96-9484-5aedca6cb3f6
 */
export function trackAgentMessageSpec(agentMessage: MessageReceived & ContextsOrTimestamp<Agent | Message>, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: '79fa7504-66b1-4e96-9484-5aedca6cb3f6',
        version: 2,
        name: 'Agent Message',
        data_product_id: 'fb649b24-5201-404f-a0ae-3fcc5d621271',
        data_product_name: 'Agentic Assistant',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(agentMessage.context)
        ? [...agentMessage.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedAgentMessage = {
        ...agentMessage,
        context,
    };

    trackMessageReceived<Agent | Message | EventSpecification>(modifiedAgentMessage, trackers);
}
/**
 * Tracks a FullSearch event specification.
 * ID: c2a5edb5-594f-444f-9d22-eed1081b41bf
 */
export function trackFullSearchSpec(fullSearch: SearchPerformedFullSearch & ContextsOrTimestamp<ArticleFullSearch>, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'c2a5edb5-594f-444f-9d22-eed1081b41bf',
        version: 5,
        name: 'Full Search',
        data_product_id: '98f633e6-ab32-43a8-8e07-0d6124da0ee7',
        data_product_name: 'Editorial Content Engagement',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(fullSearch.context)
        ? [...fullSearch.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedFullSearch = {
        ...fullSearch,
        context,
    };

    trackSearchPerformedFullSearch<ArticleFullSearch | EventSpecification>(modifiedFullSearch, trackers);
}
/**
 * Tracks a SelectAPlan event specification.
 * ID: d30cf2d2-23ed-4faa-889b-bb776182d8ab
 */
export function trackSelectAPlanSpec(selectAPlan: SubscriptionWorkflowSelectAPlan & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'd30cf2d2-23ed-4faa-889b-bb776182d8ab',
        version: 7,
        name: 'Select a Plan',
        data_product_id: 'ead1f30f-1234-4350-a112-02003991e391',
        data_product_name: 'Customer Acquisition',
        data_product_domain: 'Marketing'
    });

    const context = Array.isArray(selectAPlan.context)
        ? [...selectAPlan.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedSelectAPlan = {
        ...selectAPlan,
        context,
    };

    trackSubscriptionWorkflowSelectAPlan<Record<string, unknown> | EventSpecification>(modifiedSelectAPlan, trackers);
}
/**
 * Tracks a UserMessage event specification.
 * ID: e604200b-01ff-4da3-aa96-61887f93e7d5
 */
export function trackUserMessageSpec(userMessage: MessageSent & ContextsOrTimestamp<Message>, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'e604200b-01ff-4da3-aa96-61887f93e7d5',
        version: 2,
        name: 'User Message',
        data_product_id: 'fb649b24-5201-404f-a0ae-3fcc5d621271',
        data_product_name: 'Agentic Assistant',
        data_product_domain: 'Product'
    });

    const context = Array.isArray(userMessage.context)
        ? [...userMessage.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedUserMessage = {
        ...userMessage,
        context,
    };

    trackMessageSent<Message | EventSpecification>(modifiedUserMessage, trackers);
}
/**
 * Tracks a EnterSubscriptionFlow event specification.
 * ID: eca878e2-aa58-48d5-b3dd-86980ec2fc03
 */
export function trackEnterSubscriptionFlowSpec(enterSubscriptionFlow: SubscriptionWorkflowEnterSubscriptionFlow & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'eca878e2-aa58-48d5-b3dd-86980ec2fc03',
        version: 3,
        name: 'Enter Subscription Flow',
        data_product_id: 'ead1f30f-1234-4350-a112-02003991e391',
        data_product_name: 'Customer Acquisition',
        data_product_domain: 'Marketing'
    });

    const context = Array.isArray(enterSubscriptionFlow.context)
        ? [...enterSubscriptionFlow.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedEnterSubscriptionFlow = {
        ...enterSubscriptionFlow,
        context,
    };

    trackSubscriptionWorkflowEnterSubscriptionFlow<Record<string, unknown> | EventSpecification>(modifiedEnterSubscriptionFlow, trackers);
}
/**
 * Tracks a LoginSuccess event specification.
 * ID: fbda2b20-8c46-4750-833b-bf9cbcaf165e
 */
export function trackLoginSuccessSpec(loginSuccess: LoginLoginSuccess & ContextsOrTimestamp, trackers?: string[]){
    const eventSpecificationContext = createEventSpecification({
        id: 'fbda2b20-8c46-4750-833b-bf9cbcaf165e',
        version: 2,
        name: 'Login Success',
        data_product_id: 'ead1f30f-1234-4350-a112-02003991e391',
        data_product_name: 'Customer Acquisition',
        data_product_domain: 'Marketing'
    });

    const context = Array.isArray(loginSuccess.context)
        ? [...loginSuccess.context, eventSpecificationContext]
        : [eventSpecificationContext];

    const modifiedLoginSuccess = {
        ...loginSuccess,
        context,
    };

    trackLoginLoginSuccess<Record<string, unknown> | EventSpecification>(modifiedLoginSuccess, trackers);
}


